version: "3.9"
services:
    nginx_http:
        build:
            context: pkg/nginx-http
            args:
                - PROXY_DOMAIN
        ports:
            - 80:80
        restart: always
        volumes:
            - /var/www/letsencrypt:/var/www/letsencrypt

    certbot:
        image: certbot/certbot:latest
        depends_on:
            - nginx_http
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
            - /var/www/letsencrypt:/var/www/letsencrypt
        entrypoint:
            - sh
            - -c
        command:
            - |
              mkdir -p /var/www/letsencrypt
              certbot certonly --webroot -w /var/www/letsencrypt -d ${PROXY_DOMAIN} -m ${LETSENCRYPT_EMAIL} --agree-tos --non-interactive

    ddns:
        build:
            context: pkg/ddns
            args:
                - ROOT_DOMAIN
                - DNS_TARGET_PASS
                - DNS_TARGET_IP
        depends_on:
            - certbot
        expose:
            - 5300
        restart: always

    nginx:
        build:
            context: pkg/nginx
            args:
                - ROOT_DOMAIN
                - PROXY_DOMAIN
        depends_on:
            - ddns
        ports:
            - 443:443
            - 34197:34197/udp
            - 16261:16261/udp
            - 21025:21025/tcp
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
