name: Deploy

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true

            - name: Evaluate Templates
              env:
                PROXY_DOMAIN: ${{ secrets.PROXY_DOMAIN }} # example.com
                PROXY_HOST: ${{ secrets.PROXY_HOST }} # proxy.example.com
                CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                DDNS_LAB1_PASS: ${{ secrets.DDNS_LAB1_PASS }}
                DDNS_LAB1_IP: ${{ secrets.DDNS_LAB1_IP }}
                DDNS_LAB2_PASS: ${{ secrets.DDNS_LAB2_PASS }}
                DDNS_LAB2_IP: ${{ secrets.DDNS_LAB2_IP }}
                PROXY_LAB2_DOMAIN: ${{ secrets.PROXY_LAB2_DOMAIN }} 
              run: |
                  envsubst < compose.yml.tpl > compose.yml
                  envsubst < pkg/traefik/traefik.yml.tpl > pkg/traefik/traefik.yml
                  envsubst < pkg/traefik/config/proxy.yml.tpl > pkg/traefik/config/proxy.yml
                  envsubst < pkg/ddns/config.yml.tpl > pkg/ddns/config.yml
                  envsubst < pkg/ddns/db.yml.tpl > pkg/ddns/db.yml

            - name: Push files to DEPLOY_HOST
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.DEPLOY_HOST }}
                username: ${{ secrets.DEPLOY_USERNAME }}
                key: ${{ secrets.DEPLOY_SSH_KEY }}
                rm: true
                source: "."
                target: "/opt/lab-ddns-proxy"

            - name: Deploy
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.DEPLOY_HOST }}
                username: ${{ secrets.DEPLOY_USERNAME }}
                key: ${{ secrets.DEPLOY_SSH_KEY }}
                script: |
                  cd /opt/lab-ddns-proxy
                  docker compose up -d --build --remove-orphans --force-recreate

